name: flutter_quran
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  translator: '^0.1.0+7'
  path_provider: '^0.5.0+1'
  objectdb: '^1.0.5'
  http: '^0.12.0+1'
  built_value: ^6.3.2
  built_collection: '>=2.0.0 <5.0.0'
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.3.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assests/images/leading.png
    - assests/images/quran.png
    - assests/images/namaz.png
    - assests/images/tasbee.png
    - assests/images/salat.png

    - assests/json/1.json
    - assests/json/2.json
    - assests/json/3.json
    - assests/json/4.json
    - assests/json/5.json
    - assests/json/6.json
    - assests/json/7.json
    - assests/json/8.json
    - assests/json/9.json
    - assests/json/10.json
    - assests/json/11.json
    - assests/json/12.json
    - assests/json/13.json
    - assests/json/14.json
    - assests/json/15.json
    - assests/json/16.json
    - assests/json/17.json
    - assests/json/18.json
    - assests/json/19.json
    - assests/json/20.json
    - assests/json/21.json
    - assests/json/22.json
    - assests/json/23.json
    - assests/json/24.json
    - assests/json/25.json
    - assests/json/26.json
    - assests/json/27.json
    - assests/json/28.json
    - assests/json/29.json
    - assests/json/30.json
    - assests/json/31.json
    - assests/json/32.json
    - assests/json/33.json
    - assests/json/34.json
    - assests/json/35.json
    - assests/json/36.json
    - assests/json/37.json
    - assests/json/38.json
    - assests/json/39.json
    - assests/json/40.json
    - assests/json/41.json
    - assests/json/42.json
    - assests/json/43.json
    - assests/json/44.json
    - assests/json/45.json
    - assests/json/46.json
    - assests/json/47.json
    - assests/json/48.json
    - assests/json/49.json
    - assests/json/50.json
    - assests/json/51.json
    - assests/json/52.json
    - assests/json/53.json
    - assests/json/54.json
    - assests/json/55.json
    - assests/json/56.json
    - assests/json/57.json
    - assests/json/58.json
    - assests/json/59.json
    - assests/json/60.json
    - assests/json/61.json
    - assests/json/62.json
    - assests/json/63.json
    - assests/json/64.json
    - assests/json/65.json
    - assests/json/66.json
    - assests/json/67.json
    - assests/json/68.json
    - assests/json/69.json
    - assests/json/71.json
    - assests/json/72.json
    - assests/json/73.json
    - assests/json/74.json
    - assests/json/75.json
    - assests/json/76.json
    - assests/json/77.json
    - assests/json/78.json
    - assests/json/79.json
    - assests/json/80.json
    - assests/json/81.json
    - assests/json/82.json
    - assests/json/83.json
    - assests/json/84.json
    - assests/json/85.json
    - assests/json/86.json
    - assests/json/87.json
    - assests/json/88.json
    - assests/json/89.json
    - assests/json/90.json
    - assests/json/91.json
    - assests/json/92.json
    - assests/json/93.json
    - assests/json/94.json
    - assests/json/95.json
    - assests/json/96.json
    - assests/json/97.json
    - assests/json/98.json
    - assests/json/99.json
    - assests/json/100.json
    - assests/json/101.json
    - assests/json/102.json
    - assests/json/103.json
    - assests/json/104.json
    - assests/json/105.json
    - assests/json/106.json
    - assests/json/107.json
    - assests/json/108.json
    - assests/json/109.json
    - assests/json/110.json
    - assests/json/111.json
    - assests/json/112.json
    - assests/json/113.json
    - assests/json/114.json
    - assests/json/quran.json





    #   To add assets to your application, add an assets section, like this:
#    assets:
#    - images/leading.png
#    - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
